app/lk/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('history/', views.history),
    path('history/<int:id_record>/', views.annulment_record),

    path('record/', views.specialists),
    path('record/<int:id_speciality>/', views.choice_of_doctor),
    path('record/<int:id_speciality>/<int:id_doctor>/timetable', views.record),
    path('record/<int:id_speciality>/<int:id_doctor>/info', views.doc_profile),

    path('schedule/', views.schedule_specialists),
    path('schedule/<int:id_speciality>/', views.schedule_choice_of_doctor),
    path('schedule/<int:id_speciality>/<int:id_doctor>/timetable',
         views.schedule_record),
    path('schedule/<int:id_speciality>/<int:id_doctor>/info', views.doc_profile),

    # подтягивание юрлов с managment
    path('', include('managment.urls')),

    path('info/', views.record_info),

    path('warning/', views.warning),
    # поиск врача Ajax
    path('doc_search/', views.doc_search),
]

app/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainApp.urls')),
    path('lk/', include('lk.urls')),
    path('admin/', admin.site.urls),
    # подтягивание юрлов с authentication
    path('', include('authentication.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'mainApp.views.page404'
handler500 = 'mainApp.views.page500'

app/lk/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models


class Speciality(models.Model):
    class Meta:
        verbose_name = 'специальность'
        verbose_name_plural = 'Специальности врачей'

    speciality = models.CharField("Специальность", max_length=100)

    def __str__(self):
        return self.speciality


class Doctors(models.Model):
    class Meta:
        verbose_name = 'врача'
        verbose_name_plural = 'Врачи'
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, default=None)
    name = models.CharField("ФИО", max_length=100, default='')
    DAYS_OF_THE_WEEK = (
        ('ПН', 'Понедельник'),
        ('ВТ', 'Вторник'),
        ('СР', 'Среда'),
        ('ЧТ', 'Четверг'),
        ('ПТ', 'Пятнца'),
        ('СБ', 'Суббота'),
        ('ВС', 'Воскресенье'),
    )
    specialty = models.ForeignKey(Speciality, on_delete=models.CASCADE)
    start_day_work = models.CharField(
        "Начало работы",
        max_length=60,
        choices=DAYS_OF_THE_WEEK,
        default='ПН'
    )
    end_day_work = models.CharField(
        "Конец работы",
        max_length=60,
        choices=DAYS_OF_THE_WEEK,
        default='ПТ'
    )
    room = models.IntegerField("Кабинет", default=0)
    avatar = models.ImageField(
        "Аватар",
        blank=True,
        upload_to='doc_avatar',
        default="default_doc.png"
    )

    def get_full_doc_str(self):
        return self.specialty + " " + self.name

    def __str__(self):
        return self.name


class Schedule(models.Model):
    class Meta:
        verbose_name = 'расписание'
        verbose_name_plural = 'Расписание врача'

    doctor = models.OneToOneField(
        Doctors,
        verbose_name='Доктор',
        on_delete=models.DO_NOTHING
    )

    mo_start = models.TimeField("Понедельник начало", blank=True)
    mo_end = models.TimeField("Понедельник конец", blank=True)

    tu_start = models.TimeField("Вторник начало", blank=True)
    tu_end = models.TimeField("Вторник конец", blank=True)

    we_start = models.TimeField("Среда начало", blank=True)
    we_end = models.TimeField("Среда конец", blank=True)

    th_start = models.TimeField("Четверг начало", blank=True)
    th_end = models.TimeField("Четверг конец", blank=True)

    fr_start = models.TimeField("Пятница начало", blank=True)
    fr_end = models.TimeField("Пятница конец", blank=True)

    time_step = models.TimeField(
        "Время на одного пациента",
        blank=True,
        default=datetime.time(00, 00)
    )

    def __str__(self):
        return self.doctor.name

app/managment/models.py
from django.utils import timezone
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from lk.models import Doctors


# таблица всех записай
class Record(models.Model):
    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'Записи'

    STATUSES = (
        ('Открыт', 'Открыт'),
        ('Закрыт', 'Закрыт'),
    )
    user = models.ForeignKey(
        User,
        verbose_name='Пациент',
        on_delete=models.CASCADE,
        default=None
    )
    doctor = models.ForeignKey(
        Doctors,
        verbose_name='Доктор',
        on_delete=models.CASCADE,
        default=None
    )
    time = models.DateTimeField("Дата/время", default=timezone.now, blank=True)
    status = models.CharField(
        "Статус записи",
        max_length=60,
        choices=STATUSES,
        default='Открыт'
    )
    diagnosis = models.TextField(
        "Диагноз", max_length=255, default='', blank=True)

    def __str__(self):
        return self.user.profile.fio


class Notworkday(models.Model):
    class Meta:
        verbose_name = 'нерабочий день'
        verbose_name_plural = 'Нерабочие дни'

    doctor = models.ForeignKey(
        Doctors,
        verbose_name='Доктор',
        on_delete=models.DO_NOTHING,
        default=None
    )

    not_work_day = models.DateField(
        'Нерабочие дни', blank=True, default=datetime.min.date())

    def __str__(self):
        return str(self.not_work_day)


class Contact(models.Model):
    class Meta:
        verbose_name = 'обратная связь'
        verbose_name_plural = 'Обратная связь'

    subject = models.CharField('Тема сообщения', max_length=100)
    sender = models.EmailField('Email')
    message = models.TextField('Сообщение', max_length=800)

    answer = models.TextField('Ответ', max_length=800, blank=False, default='')
    send = models.BooleanField('Ответ написан', default=False)
    answered = models.BooleanField('Ответ отправлен', default=False)

    def __str__(self):
        return self.subject

app/lk/views.py
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.http import JsonResponse
# сброс пароля
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
# stackoverflow.com/a/770078/63097
from django.db.models import Q
# доступ к вьюшке только залогиненому пользователю
from django.contrib.auth.decorators import login_required
from managment.models import Record, Notworkday
from .models import Doctors, Speciality


@login_required
def index(request):
    if request.POST:
        new_pass_form = PasswordChangeForm(
            user=request.user, data=request.POST)
        if new_pass_form.is_valid():
            new_pass_form.save()
            update_session_auth_hash(request, new_pass_form.user)
            return render(request, 'lk/lk-main.html', {
                'new_pass_form': new_pass_form,
                'succses_message': "Пароль успешно сменён"
            })
        return render(request, 'lk/lk-main.html', {'new_pass_form': new_pass_form})
    else:
        new_pass_form = PasswordChangeForm(user=request.user)
        return render(request, 'lk/lk-main.html', {'new_pass_form': new_pass_form})


@login_required
def history(request):
    recs = Record.objects.filter(user_id=request.user.id)
    filter_get = ""
    order_get = ""
    page_get = ""
    # Сортировка
    if "order" in request.GET:
        order_status = request.GET['order']
        order_get = '&order=' + order_status
        if order_status == '1':
            order_status = 'time'
        elif order_status == '-1':
            order_status = '-time'
        elif order_status == '2':
            order_status = 'doctor__specialty'
        elif order_status == '-2':
            order_status = '-doctor__specialty'
        elif order_status == '3':
            order_status = 'doctor__name'
        elif order_status == '-3':
            order_status = '-doctor__name'
        recs = recs.order_by(order_status)
        filter_text = "Все"
    else:
        recs = recs.order_by('-time')
        filter_text = "Все"

    # Фильтр
    if "filter" in request.GET:
        filter_status = request.GET['filter']
        filter_get = "&filter=" + filter_status
        if filter_status == '1':
            recs = recs.filter(status='Открыт')
            filter_text = 'Открытые'
        elif filter_status == '2':
            recs = recs.filter(status='Закрыт')
            filter_text = 'Закрытые'

    # Пагинация
    from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
    paginator = Paginator(recs, 8)
    if "page" in request.GET:
        page = request.GET['page']
    else:
        page = "1"
    page_get = 'page=' + page
    try:
        recs = paginator.page(page)
    except PageNotAnInteger:
        # Если в гет передана не int.
        page = paginator.page(1)
    except EmptyPage:
        # Если число не верно.
        page = paginator.page(paginator.num_pages)

    args = {
        'records': recs,
        'filter_text': filter_text,
        'pg': page_get,
        'fg': filter_get,
        'og': order_get,
    }
    return render(request, 'lk/history.html', args)


@login_required
def annulment_record(request, id_record):
    """Отмена записи"""
    rec = Record.objects.get(id=id_record)
    rec.delete()
    return redirect('/lk/history/')
# -----------------------------------------------

# --------------record-------------------
# First step
@login_required
def specialists(request):
    specialitys = Speciality.objects.all()
    args = {'specialitys': specialitys}
    return render(request, 'lk/specialists.html', args)

# Second step or skip
@login_required
def choice_of_doctor(request, id_speciality):
    all_docs = Doctors.objects.filter(specialty__id=id_speciality)[:20]
    spec = Speciality.objects.get(id=id_speciality).speciality
    args = {'all_doctors': all_docs, 'speciality': spec}
    return render(request, 'lk/choice_of_doctor.html', args)

# final step
@login_required
def record(request, id_speciality, id_doctor):
    # доктор
    doctor = Doctors.objects.get(user__id=id_doctor)

    # подтягивание списка занятых ячеек
    busy_time_this_doctor = Record.objects.filter(doctor__user__id=id_doctor)
    busy_time_list = []

    for busy_time in busy_time_this_doctor:
        busy_time_list.append(busy_time.time)

    # --------------- запись пациента ------------------
    if request.GET:
        rec_date = request.GET['rec_date']
        rec_date = datetime.strptime(rec_date, r"%d-%m-%y-%H-%M")
        # записи пациента на сегодня к этому доктору
        today_recorded = Record.objects.filter(
            doctor__user__id=id_doctor,
            user=request.user,
            time__contains=rec_date.date()
        )

        if rec_date in busy_time_list:
            # занято
            return redirect('/lk/warning/?war=1')
        elif today_recorded:
            # сегодня уже записан
            return redirect('/lk/warning/?war=2')
        else:
            new_rec = Record()
            new_rec.doctor = doctor
            new_rec.user = request.user
            new_rec.time = rec_date
            new_rec.save()
            return redirect('/lk/history/')
    # --------------------------------------------------

    # текущяя дата +6 дней для шаблона
    now_plus_five = datetime.now() + timedelta(days=6)

    # шаг времени на 1 пациента
    time_step = doctor.schedule.time_step.minute
    # создание пустых листов
    days = {
        'day_1': [],
        'day_2': [],
        'day_3': [],
        'day_4': [],
        'day_5': [],
        'day_6': [],
        'day_7': []
    }
    one_weekday = []

    # создание обьектов datetime начала и конца приёма
    def get_work_time(num_weekday, status, the_date):
        if num_weekday == 1:
            if status == 'start':
                return datetime.combine(the_date, doctor.schedule.mo_start)
            if status == 'end':
                return datetime.combine(the_date, doctor.schedule.mo_end)
        if num_weekday == 2:
            if status == 'start':
                return datetime.combine(the_date, doctor.schedule.tu_start)
            if status == 'end':
                return datetime.combine(the_date, doctor.schedule.tu_end)
        if num_weekday == 3:
            if status == 'start':
                return datetime.combine(the_date, doctor.schedule.we_start)
            if status == 'end':
                return datetime.combine(the_date, doctor.schedule.we_end)
        if num_weekday == 4:
            if status == 'start':
                return datetime.combine(the_date, doctor.schedule.th_start)
            if status == 'end':
                return datetime.combine(the_date, doctor.schedule.th_end)
        if num_weekday == 5:
            if status == 'start':
                return datetime.combine(the_date, doctor.schedule.fr_start)
            if status == 'end':
                return datetime.combine(the_date, doctor.schedule.fr_end)

    def create_full_list(request, id_doctor):
        weekday = datetime.now().isoweekday()
        today = datetime.now().date()

        # ------ создание списка отменённых дней ------
        not_work_days_list = []
        not_work_days = Notworkday.objects.filter(doctor__user__id=id_doctor)
        for nwd in not_work_days:
            not_work_days_list.append(nwd.not_work_day)

        # 7 дней(от 1 до 9)

        for i in range(1, 8):
            start = get_work_time(weekday, 'start', today)
            end = get_work_time(weekday, 'end', today)

            # если не выходные и нет в списке отменённых дней, start.hour - в админке 0
            if start is not None and not today in not_work_days_list and start.hour:

                # основа
                while start <= end:
                    # распределение классов, проверка занятости
                    cel_class = ""
                    if start < datetime.now():
                        cel_class = "miss"
                    elif start in busy_time_list:
                        cel_class = "busy"
                    else:
                        cel_class = "free"

                    days['day_{}'.format(i)].append({
                        'time': start,
                        'class': cel_class
                    })
                    start += timedelta(minutes=time_step)

            # заполнение дня недели
            one_weekday.append(today)
            # сброс дня недели до понедельника
            weekday += 1
            if weekday == 8:
                weekday = 1

            today = today + timedelta(days=1)
            # print("Today:", today)

    create_full_list(request, id_doctor)

    from itertools import zip_longest
    timetbl = zip_longest(
        days['day_1'],
        days['day_2'],
        days['day_3'],
        days['day_4'],
        days['day_5'],
        days['day_6'],
        days['day_7']
    )
    args = {
        'doctor': doctor,
        'timetbl': timetbl,
        'one_weekday': one_weekday,
        'now_plus_five': now_plus_five
    }

    return render(request, 'lk/record.html', args)

# --------------schedule-------------------


def schedule_specialists(request):
    specialitys = Speciality.objects.all()
    args = {'specialitys': specialitys}
    return render(request, 'lk/specialists.html', args)

# Second step or skip


def schedule_choice_of_doctor(request, id_speciality):
    all_docs = Doctors.objects.filter(specialty__id=id_speciality)[:20]
    spec = Speciality.objects.get(id=id_speciality).speciality
    args = {'all_doctors': all_docs, 'speciality': spec}
    return render(request, 'lk/schedule_choice_of_doctor.html', args)

# final step


def schedule_record(request, id_speciality, id_doctor):
    doctor = Doctors.objects.get(user__id=id_doctor)
    start_add = []
    end_add = []
    start_add.append(doctor.schedule.mo_start)
    start_add.append(doctor.schedule.tu_start)

app/lk/templates/lk/about_info.html
{% extends "lk/wrapper.html" %}
{% block title %}О услугах{% endblock %}

{% block content %}

  <section class="lk-content">
    <div class="wrap rec-info">
      <h2 class="title">Запись на приём</h2>
      <div class="rec-description">
        <ul class="allOk">
          <li>Услуга является бесплатной.</li>
          <li>Запись к врачу производится на неделю вперёд.</li>
          <li>Обновление расписаний врачей на сайте происходит ежедневно в 00:00.</li>
          <li>Услуга предназначена для записи пациентов на ПЛАНОВЫЙ прием к врачам.</li>
          <li>В случае отсутствия записи, в приёме Вам могут отказать.</li>
          <li>Вы можете записать к врачу не только себя, но и своих близких.</li>
        </ul>
        {% if not user.is_authenticated %}
        <div class="pls-auth">Для доступа к услуге авторизуйтесь, пожалуйста.</div>
        {% endif %}
        
      </div>
    </div>
  </section>

  <!-- модалка на подтверждение отмены записи -->
  <div id="annulment-dialog" style="display: none;">
    <span class="close"></span>
    <h1>Отмена записи</h1>
    <p>В случае отмены записи, это время становиться доступно всем желающим.</p>
    <p>
      Вы уверены что хотите отменить запись?
    </p>
    <div class="separator20"></div>
    <p>
      <a href="javascript:;" class="btn green-button" id="annulment-button">Подтвердить</a>
      <a href="javascript:;" class="btn gray-button" id="modal-close-button">Отменить</a>
    </p>	
  </div>
</div>

{% endblock %}

app/lk/templates/lk/choice_of_doctor.html
{% extends "lk/wrapper.html" %}
{% block title %}Запись на приём{% endblock %}

{% block content %}

  <section class="lk-content">
	  <div class="wrap">
		  <h2 class="title">Записаться на приём к <span>{{speciality}}у</span></h2>
		  <div class="add-balance-info">
			<p>Выберите врача и нажмите на кнопку (записаться), затем выберете время.</p>
		  </div>
		  <div class="table">
			<table>
			  <thead>
				<td>ФИО</td>
				<td>Режим работы</td>
				<td>Расписание</td>
				<td>Карточка врача</td>
			  </thead>
			  <tbody>
					{% for doc in all_doctors %}
					<tr>
						<td>{{doc.name}}</td>
						<td>{{doc.start_day_work}} - {{doc.end_day_work}}</td>
						<td><a href="{{ doc.user.id }}/timetable" class="edit">Записаться</a></td>
						<td><a href="{{ doc.user.id }}/info" class="card">О враче</a></td>
					</tr>
					{% endfor %}
			  </tbody>
			</table>
		  </div>
	  </div>
	</section>
</div>

{% endblock %}

app/lk/templates/lk/contact.html
{% extends "lk/wrapper.html" %}
{% block title %}Обратная связь{% endblock %}

{% block content %}

  <section class="lk-content">
    <div class="wrap contact">

      <h2 class="title">Форма обратной связи</h2>

      <div class="add-balance-info">
        <p>Если у вас возникли вопросы, напишите в службу обратной связи:</p>
      </div>

      <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
      <div>
        <label for="id_subject">Тема:</label>
        {{ form.subject.errors }}
        {{ form.subject }}
      </div>
      <div>
        <label for="id_sender">E-mail:</label>
        {{ form.sender.errors }}
        {{ form.sender }}
      </div>
      <div>
        <label for="id_message">Сообщение:</label>
        {{ form.message.errors }}
        {{ form.message }}
      </div>
      <input class="contact-btn" type="submit" value="Отправить"/>
    </form>
    <div class="h-block" style="display: none;">{{ valid_status }}</div>
    </div>
  </section>
  
  <!-- модалка об успешном запросе в обратную связь -->
  <div id="contact-dialog" style="display: none;">
    <!-- <span class="close"></span> -->
    <h1>Обратная связь</h1>
    <p>Ваш вопрос успешно доставлен и в скором времени на вашу почту придет ответ.</p>
    <div class="separator20"></div>
    <p>
      <a href="/" class="btn green-button">На главную</a>
    </p>	
  </div>
</div>

{% endblock %}

app/lk/templates/lk/doc_profile.html
{% extends "lk/wrapper.html" %}
{% block title %}Карточка врача{% endblock %}

{% block content %}
  <section class="lk-content">
   <div class="wrap">
    <h2 class="title">Карточка врача</h2>
      <div class="add-balance-info">
        <p>Здесь отображаются данные врача.</p>
      </div>
      <div class="doc-profile">
        <div class="doc-avatar">
          <img src="{{ doctor.avatar.url }}">
        </div>
        <div class="doc-info">
          <div class="doc-name">{{ doctor.name }}</div>
          {% comment %} get_fieldname_display - полное отображение из кортежа {% endcomment %}
          <p><span class="info-label">Сециальность:</span> {{ doctor.specialty }}</p>
          <p><span class="info-label">Начало работы:</span> {{ doctor.get_start_day_work_display }}</p>
          <p><span class="info-label">Конец работы:</span> {{ doctor.get_end_day_work_display }}</p>
          <p><span class="info-label">Кабинет:</span> {{ doctor.room }}</p>
          <a href="timetable" class="gr-btn">Расписание</a>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

app/lk/templates/lk/history.html
{% extends "lk/wrapper.html" %}
{% block title %}История{% endblock %}

{% block content %}

  <section class="lk-content">
   <div class="wrap">
    <h2 class="title">Личный кабинет - мои записи</h2>
      <div class="add-balance-info">
        <p>Здесь отображаются ваша история записей к врачам.</p>
      </div>
      <div class="dst">
        <div class="withdrawal-operation">
          <div class="table">
            <ul class="filter-block">
              <li><a href="?{{ pg }}{{ og }}">Все</a></li>
              <li><a href="?{{ pg }}&filter=1{{ og }}">Открытые</a></li>
              <li><a href="?{{ pg }}&filter=2{{ og }}">Закрытые</a></li>
            </ul>
  
            <div class="head">
              <h2 class="head-title">История записей</h2>
              <div class="filter">
                Фильтр: <span id="filter-text">{{ filter_text }}</span><img src="/static/images/arr-ico.png">
              </div>
            </div>
            <table>
              <thead class="tbl-head-order">
                <td>
                  <a href="?{{ pg }}{{ fg }}&order=1" class="date-link" data-is-active="true"> <nobr>Дата и время</nobr>
                  </a>
                </td>
                <td>
                  <a href="?{{ pg }}{{ fg }}&order=2" class="date-link">Специаль<wbr>ность
                  </a>
                </td>
                <td>
                  <a href="?{{ pg }}{{ fg }}&order=3" class="date-link">ФИО врача
                  </a>
                </td>
                <td>Статус</td>
                <td>Отмена</td>
              </thead>
              <tbody>
                {% for item in records %}
                <tr>
                  <td>{{ item.time }}</td>
                  <td>{{ item.doctor.specialty }}</td>
                  <td>{{ item.doctor.name }}</td>
                  <td>
                    {{ item.status }}
                  </td>
                  <td class="annulment">
                    {% if item.status == 'Открыт' %}
                    <div class="annulment-block" data-rec-id="{{ item.id }}" >
                      <img src="/static/images/delete.png" alt="Отменить запись">
                    </div>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% if not records %}
              <div class="no-records">Записей нет</div>
            {% endif %}
          </div>
        </div>

        <div class="pagination">
          {% if records.has_other_pages %}
            {% if records.has_previous %}
                <a href="?page={{ records.previous_page_number }}{{ fg }}{{ og }}">&laquo;</a>
            {% else %}
                <a href="#" class="disabled">&laquo;</a>
            {% endif %}
            {% for num in records.paginator.page_range %}
                {% if num == records.number %}
                    <span class="current">{{ num }}</span>
                {% else %}
                    <a href="?page={{ num }}{{ fg }}{{ og }}">{{ num }}</a>
                {% endif %} 
            {% endfor %}
            {% if records.has_next %}
                <a href="?page={{ records.next_page_number }}{{ fg }}{{ og }}">&raquo;</a>
            {% else %}
                <a href="#" class="disabled">&raquo;</a>
            {% endif %} 
          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- модалка на подтверждение отмены записи -->
  <div id="annulment-dialog" style="display: none;">
    <span class="close"></span>
    <h1>Отмена записи</h1>
    <p>В случае отмены записи, это время может занять другой человек.</p>
    <p>
      Вы уверены что хотите отменить запись?
    </p>
    <div class="separator20"></div>
    <p>
      <a href="javascript:;" class="btn green-button" id="annulment-button">Подтвердить</a>
      <a href="javascript:;" class="btn gray-button" id="modal-close-button">Отмена</a>
    </p>	
  </div>
</div>

{% endblock %}

app/lk/templates/lk/lk-main.html
{% extends "lk/wrapper.html" %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}
  <section class="lk-content">
   <div class="wrap">
     <div id="test"></div>
    <h2 class="title">Добро пожаловать в личный кабинет</h2>
      <div class="add-balance-info">
        <p>Здесь отображаются ваши данные.</p>
      </div>
      <div class="user-profile">
          <div class="user-avatar">
            {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}">
            {% else %}
            <img src="/media/default.png">
            {% endif %}
          </div>
          
        <p><span class="info-label">Login:</span> {{ user.username }}</p>
        <p><span class="info-label">Email:</span> {{ user.email }}</p>
        <p><span class="info-label">Фамилия:</span> {{ user.profile.get_only_surname }}</p>
        <p><span class="info-label">Имя:</span> {{ user.profile.get_only_firstname }}</p>
        <p><span class="info-label">Отчество:</span> {{ user.profile.get_only_patronymic }}</p>
        <a href="#" id="change_pass_link">Смена пароля</a>
        <div id="change_pass_block">
          
          {% if new_pass_form.errors %}
          <div class="error-block alert alert-danger">
            {% for error in new_pass_form.old_password.errors %}
              <p>{{ error|escape }}</p>
            {% endfor %}
            {% for error in new_pass_form.new_password1.errors %}
              <p>{{ error|escape }}</p>
            {% endfor %}
            {% for error in new_pass_form.new_password2.errors %}
              <p>{{ error|escape }}</p>
            {% endfor %}
          </div>
          {% endif %}
          
          <form action="" method="POST">
            {% csrf_token %}
            <p>
              <label for="id_old_password">Старый пароль*</label>
              {{ new_pass_form.old_password }}
            </p>
            <p>
              <label for="id_new_password1">Новый пароль*</label>
              {{ new_pass_form.new_password1 }}
            </p>
            <p>
              <label for="id_new_password2">Новый пароль еще раз*</label>
              {{ new_pass_form.new_password2 }}
            </p>
            <input type="submit" value="Сменить пароль">
          </form>
        </div>
        {% if succses_message %}
          <div class="succsec-block alert alert-success">{{succses_message}}</div>
        {% endif %}
      </div>
    </div>
  </section>
</div>

{% endblock %}

app/lk/templates/lk/warnings.html
{% extends "lk/wrapper.html" %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}
  <section class="lk-content">
   <div class="wrap warnings-page">
      <p class="alert alert-danger">Произошла ошибка</p>
      <p class="alert alert-warning warning_msg">{{ error_msg }}</p>
      <a href="{{ old_link }}" class="btn">Вренуться обратно</a>
    </div>
  </section>
</div>

{% endblock %}