app/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup),
    path('login/', views.login),
    # выход
    path('logout/', views.logout),

    path('checkUserName/', views.check_user_name),
]

app/lk/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('history/', views.history),
    path('history/<int:id_record>/', views.annulment_record),

    path('record/', views.specialists),
    path('record/<int:id_speciality>/', views.choice_of_doctor),
    path('record/<int:id_speciality>/<int:id_doctor>/timetable', views.record),
    path('record/<int:id_speciality>/<int:id_doctor>/info', views.doc_profile),

    path('schedule/', views.schedule_specialists),
    path('schedule/<int:id_speciality>/', views.schedule_choice_of_doctor),
    path('schedule/<int:id_speciality>/<int:id_doctor>/timetable',
         views.schedule_record),
    path('schedule/<int:id_speciality>/<int:id_doctor>/info', views.doc_profile),

    # подтягивание юрлов с managment
    path('', include('managment.urls')),

    path('info/', views.record_info),

    path('warning/', views.warning),
    # поиск врача Ajax
    path('doc_search/', views.doc_search),
]

app/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainApp.urls')),
    path('lk/', include('lk.urls')),
    path('admin/', admin.site.urls),
    # подтягивание юрлов с authentication
    path('', include('authentication.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'mainApp.views.page404'
handler500 = 'mainApp.views.page500'

app/authentication/models.py
from django.contrib.auth.models import User
from django.db import models

# расширение таблицы User
class Profile(models.Model):
    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'Профиль пользователя'

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    fio = models.CharField("ФИО", max_length=100, default='')
    avatar = models.ImageField(
        "Аватар", blank=True, upload_to='user_avatar', default="default.png")

    def get_only_firstname(self):
        return self.fio.split(' ')[1]

    def get_only_surname(self):
        return self.fio.split(' ')[0]

    def get_only_patronymic(self):
        return self.fio.split(' ')[2]

    def __str__(self):
        return self.fio

app/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from authentication.models import Profile


class RegUserForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'login'})
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'ivan@mail.ru'})
    )

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': '**********'})
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': '**********'})
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']

    def save(self, commit=True):
        user = super(RegUserForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.password1 = self.cleaned_data['password1']
        user.password2 = self.cleaned_data['password2']

        if commit:
            user.save()

        return user


class RegProfileForm(forms.ModelForm):
    fio = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Иванов Иван Иванович'})
    )

    avatar = forms.ImageField(
        required=False,
        widget=forms.FileInput(
            attrs={'placeholder': 'Аватар', 'accept': 'image/jpeg,image/png'})
    )

    class Meta:
        model = Profile
        fields = (
            'fio',
            'avatar'
        )

    def save(self, commit=True):
        profile = super(RegProfileForm, self).save(commit=False)

        profile.fio = self.cleaned_data['fio']
        profile.avatar = self.cleaned_data['avatar']

        if commit:
            profile.save()

        return profile

    def clean_fio(self):
        data = self.cleaned_data
        return data['fio'].lower().title()

    def clean_avatar(self):
        data = self.cleaned_data
        if not data['avatar']:
            return "default.png"
        else:
            return data['avatar']

app/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import HttpResponse
from django.contrib.auth.models import User
from authentication.forms import RegUserForm, RegProfileForm
from mysite.GLOBAL_VARS import SITE_NAME


def login(request):
    '''Вход на сайт'''
    args = {}
    args['site_name'] = SITE_NAME
    if request.POST:
        u_name = request.POST['login'] or ''
        u_password = request.POST['password'] or ''
        user = auth.authenticate(username=u_name, password=u_password)
        if user is not None:
            auth.login(request, user)
            if request.user.is_staff:
                return redirect("/admin")
            else:
                return redirect("/lk/record/")
        else:
            args['log_error'] = "Логин или пароль введён неверно"
            return render(request, 'authentication/login.html', args)
    else:
        return render(request, 'authentication/login.html', args)


def logout(request):
    '''Выход с авторизации'''
    auth.logout(request)
    return redirect("/login")


def signup(request):
    '''Регистрация'''
    if request.POST:
        user_form = RegUserForm(request.POST)
        profile_form = RegProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            return redirect("/login")

        args = {'user_form': user_form,
                'profile_form': profile_form, 'site_name': SITE_NAME}
        return render(request, 'authentication/signup.html', args)
    else:
        user_form = RegUserForm()
        profile_form = RegProfileForm()

        args = {'user_form': user_form,
                'profile_form': profile_form, 'site_name': SITE_NAME}
        return render(request, 'authentication/signup.html', args)


def check_user_name(request):
    '''Ajax проверка занятости логина'''
    if request.GET:
        u_login = request.GET['u_login']
        # User.objects.values_list('username') - получить кортеж вида [(username,),(username,)]
        # User.objects.values('username') - получить словарь вида [{'username': 'username'}, {'username': 'username'}]
        if login_free(u_login):
            return HttpResponse('1')
        else:
            return HttpResponse('0')
    else:
        return redirect("/")


def login_free(u_login):
    '''Проверка занятости логина'''
    try:
        User.objects.get(username=u_login)
    except User.DoesNotExist:
        return False

    return True

app/authentication/templates/authentication/login.html
{% extends "authentication/wrapper.html" %}
{% block title %}Вход{% endblock %}

{% block content %}

<section class="form-box">
  <div class="container">
    {% if user.is_authenticated %}
    <div class="user-auth">
      <p>Вы уже вошли как <a href="/lk/">{{ user.profile.get_only_firstname }}</a></p>
      <a href="/logout" class="btn green-btn">Выйти</a>
    </div>
    {% else %}
    <div class="registration">
      <div class="title">Вход</div>
      {% if log_error %}
      <div class="text" style="display: block">
        <p>{{ log_error }}</p>
      </div>
      {% endif %}
      <form action="" method="post">
        {% csrf_token %} 
        <label>Login</label>
        <input type="text" placeholder="login" name="login">
        <label>Пароль</label>
        <input type="password" placeholder="*********" name="password" autocomplete="off">
        <button type="submit" class="btn green-btn" autocomplete="off">Войти</button>
      </form>
      <span>Еще не зарегистрированы? <a href="/signup">Регистрация</a></span>
    </div>
    {% endif %}
  </div>
</section>

{% endblock %}

app/authentication/templates/authentication/signup.html
{% extends "authentication/wrapper.html" %}
{% block title %}Регистрация{% endblock %}

{% block content %}

<section class="form-box">
  <div class="container">
    {% if user.is_authenticated %}
    <div class="user-auth">
      <p>Вы уже вошли как <a href="/lk/">{{ user.profile.get_only_firstname }}</a></p>
      <a href="/logout" class="btn green-btn">Выйти</a>
    </div>
    {% else %}
    <div class="registration">
      <div class="title">Регистрация</div>
      <div class="text">
        {% if profile_form.errors or user_form.errors %}
          <p>Произошла ошибка</p>
          {% for error in user_form.password2.errors %}
            <p>{{ error|escape }}</p>
          {% endfor %}
        {% endif %}
      </div>
      <!-- enctype="multipart/form-data" очень важна, без него не работает загрузка фото -->
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_fio">ФИО*</label>
        {{ profile_form.fio }}
        <label for="id_email">E-mail*</label>
        {{ user_form.email }}
        <label for="id_username">Логин*</label>
        {{ user_form.username }}
        <label for="id_password1">Пароль*</label>
        {{ user_form.password1 }}
        <label for="id_password2">Повторите пароль*</label>
        {{ user_form.password2 }}
        <label for="id_avatar">Аватар (не более 2mb)</label>
        {{ profile_form.avatar }}
        <span id="output"></span>
        <div class="btn green-btn" id="reg-button">Зарегистрироваться</div>
      </form>
      <span>Уже зарегистрированы? <a href="/login">Авторизоваться</a></span>
    </div>
    {% endif %}
  </div>
</section>

{% endblock %}

app/authentication/templates/authentication/wrapper.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Auth{% endblock %}</title>
  <!-- Загрузка статики -->
  {% load static %}
  <link rel="icon" href="{% static 'images/logo.png' %}">
  <link href="{% static 'css/normalize.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body class="auth">
  <div class="auth-header">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{% static 'images/logo.png' %}" alt="" class="site-logo">
        {{ site_name }}
      </a>
      {% if request.path == "/login/" %}
      <a href="/signup" class="btn dark-btn">Регистрация</a>
      {% else %}
      <a href="/login" class="btn dark-btn">Вход</a>
      {% endif %}
    </div>
  </div>
        
  {% block content %}
  {% endblock %}
  
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/reg.js' %}"></script>
</body>
</html>